### ISSUE TITLE
WorldPoint.toLocalInstance can return empty array in instances

### ISSUE THREAD

**Issue by Zoinkwiz** [Skretzo/shortest-path#97]
If you're in an instance on the surface of the world (for example, a cutscene on the surface of the game), and a worldpoint isn't within the instance area, the return from `WorldPoint.toLocalInstance` will be an empty array `[]`. This means in cutscenes the following code will throw a null exception as it tries to access it.

https://github.com/Skretzo/shortest-path/blob/2e34520adb4093bf1e0f78d180e1d0ff896e59b0/src/main/java/shortestpath/PathTileOverlay.java#L202

```
2024-10-02 00:32:19 BST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.util.NoSuchElementException: null
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:970)
	at shortestpath.PathTileOverlay.drawLine(PathTileOverlay.java:202)
	at shortestpath.PathTileOverlay.render(PathTileOverlay.java:140)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:734)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:493)
	at jh.jo(jh.java:54507)
	at jh.ct(jh.java:13389)
	at pv.jh(pv.java:4932)
	at eh.mk(eh.java:11483)
	at eh.mk(eh.java:11514)
	at dj.mj(dj.java:11378)
	at client.hm(client.java:4762)
	at client.bp(client.java:1187)
	at ba.ak(ba.java:439)
	at ba.ff(ba.java)
	at ba.run(ba.java:64846)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by Skretzo** [comment]
This was fixed in version 1.15.1 and will be live in the client after hub review has completed in a few days
